export type Sport = 'Fútbol' | 'Motor' | 'Tenis' | 'Ciclismo' | 'Atletismo' | 'Baloncesto' | 'MMA' | 'Triatlón' | 'Balonmano' | 'Maratón'

export interface Event {
  id: string
  title: string
  sport: Sport
  date: string
  time: string
  venue: string
  city: string
  country: string
  image: string
  priceFrom: number
  priceTo: number
  description: string
  partners: string[]
  featured?: boolean
}

export interface Partner {
  id: string
  name: string
  url: string
  /** price multiplier vs. event.priceFrom — used to calculate per-platform indicative price */
  fromMultiplier: number
  toMultiplier: number
  badge: string  // one-line platform description shown on detail card
}

export const PARTNERS: Partner[] = [
  {
    id: 'ticketmaster',
    name: 'Ticketmaster',
    url: 'https://www.ticketmaster.es',
    fromMultiplier: 1.0,
    toMultiplier: 1.0,
    badge: 'Plataforma oficial líder en España y Europa',
  },
  {
    id: 'stubhub',
    name: 'StubHub',
    url: 'https://www.stubhub.es',
    fromMultiplier: 1.15,
    toMultiplier: 1.25,
    badge: 'Mercado secundario global de reventas',
  },
  {
    id: 'viagogo',
    name: 'Viagogo',
    url: 'https://www.viagogo.es',
    fromMultiplier: 1.2,
    toMultiplier: 1.35,
    badge: 'Compra y vende entradas en todo el mundo',
  },
  {
    id: 'axs',
    name: 'AXS',
    url: 'https://www.axs.com',
    fromMultiplier: 1.05,
    toMultiplier: 1.1,
    badge: 'Ticketing oficial para grandes recintos',
  },
  {
    id: 'entradas',
    name: 'Entradas.com',
    url: 'https://www.entradas.com',
    fromMultiplier: 1.0,
    toMultiplier: 1.05,
    badge: 'Líder español de venta de entradas online',
  },
  {
    id: 'elcorte',
    name: 'El Corte Inglés Entradas',
    url: 'https://www.elcorteingles.es/entradas/',
    fromMultiplier: 1.0,
    toMultiplier: 1.08,
    badge: 'Entradas oficiales con garantía El Corte Inglés',
  },
  {
    id: 'ticketea',
    name: 'Ticketea',
    url: 'https://www.ticketea.com',
    fromMultiplier: 1.05,
    toMultiplier: 1.15,
    badge: 'Plataforma española de eventos y espectáculos',
  },
]

export const events: Event[] = [
  {
    id: 'el-clasico-2026',
    title: 'El Clásico: FC Barcelona vs Real Madrid',
    sport: 'Fútbol',
    date: '2026-03-28',
    time: '21:00',
    venue: 'Camp Nou',
    city: 'Barcelona',
    country: 'España',
    image: '/images/events/el-clasico.jpg',
    priceFrom: 180,
    priceTo: 950,
    description: 'El partido más esperado del año: el eterno clásico entre los dos mayores rivales del fútbol español. Una noche histórica bajo los focos del Camp Nou.',
    partners: ['ticketmaster', 'stubhub', 'viagogo'],
    featured: true,
  },
  {
    id: 'f1-gran-premio-espana-2026',
    title: 'Gran Premio de España — Fórmula 1',
    sport: 'Motor',
    date: '2026-06-07',
    time: '15:00',
    venue: 'Circuit de Barcelona-Catalunya',
    city: 'Montmeló, Barcelona',
    country: 'España',
    image: '/images/events/f1-barcelona.jpg',
    priceFrom: 120,
    priceTo: 680,
    description: 'La Fórmula 1 vuelve a España. Vive la emoción del Gran Premio en el mítico trazado catalán con las mejores escuderías del mundo.',
    partners: ['ticketmaster', 'axs', 'stubhub'],
    featured: true,
  },
  {
    id: 'barcelona-open-tenis-2026',
    title: 'Barcelona Open Banc Sabadell — Tenis ATP 500',
    sport: 'Tenis',
    date: '2026-04-22',
    time: '11:00',
    venue: 'Real Club de Tenis Barcelona',
    city: 'Barcelona',
    country: 'España',
    image: '/images/events/tennis-barcelona.jpg',
    priceFrom: 35,
    priceTo: 280,
    description: 'El mejor tenis del mundo sobre tierra batida. El torneo ATP 500 más importante de España con los mejores jugadores del ranking mundial.',
    partners: ['ticketmaster', 'entradas'],
    featured: true,
  },
  {
    id: 'mutua-madrid-open-2026',
    title: 'Mutua Madrid Open — Masters 1000',
    sport: 'Tenis',
    date: '2026-05-10',
    time: '11:00',
    venue: 'Caja Mágica',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/madrid-open-tennis.jpg',
    priceFrom: 45,
    priceTo: 420,
    description: 'El Masters 1000 más importante de la temporada sobre tierra. Noches mágicas bajo los focos de la Caja Mágica con los campeones del mundo.',
    partners: ['ticketmaster', 'axs', 'viagogo'],
    featured: true,
  },
  {
    id: 'ucl-real-madrid-2026',
    title: 'UEFA Champions League — Real Madrid vs Man City',
    sport: 'Fútbol',
    date: '2026-04-14',
    time: '21:00',
    venue: 'Estadio Santiago Bernabéu',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/ucl-bernabeu.jpg',
    priceFrom: 220,
    priceTo: 1200,
    description: 'Una de las noches más esperadas de Europa. El Real Madrid recibe al Manchester City en el mítico Santiago Bernabéu en la fase eliminatoria de la Champions League.',
    partners: ['stubhub', 'viagogo', 'ticketmaster'],
    featured: true,
  },
  {
    id: 'motogp-catalunya-2026',
    title: 'Gran Premio de Catalunya — MotoGP',
    sport: 'Motor',
    date: '2026-06-14',
    time: '14:00',
    venue: 'Circuit de Catalunya',
    city: 'Montmeló, Barcelona',
    country: 'España',
    image: '/images/events/motogp-catalunya.jpg',
    priceFrom: 60,
    priceTo: 320,
    description: 'Las motos más rápidas del mundo se enfrentan en el Circuit de Catalunya. Velocidad, adrenalina y espectáculo en la cita catalana del campeonato del mundo de MotoGP.',
    partners: ['ticketmaster', 'entradas'],
    featured: true,
  },
  {
    id: 'vuelta-espana-etapa-final-2026',
    title: 'Vuelta a España — Etapa Final Madrid',
    sport: 'Ciclismo',
    date: '2026-09-13',
    time: '16:00',
    venue: 'Paseo de la Castellana',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/vuelta-espana.jpg',
    priceFrom: 0,
    priceTo: 85,
    description: 'La gran fiesta del ciclismo español. La última etapa de la Vuelta a España llega al corazón de Madrid con el campeón camino de la Gloria.',
    partners: ['ticketmaster', 'axs'],
  },
  {
    id: 'copa-del-rey-final-2026',
    title: 'Final de la Copa del Rey',
    sport: 'Fútbol',
    date: '2026-05-23',
    time: '21:00',
    venue: 'Estadio de La Cartuja',
    city: 'Sevilla',
    country: 'España',
    image: '/images/events/copa-del-rey.jpg',
    priceFrom: 95,
    priceTo: 480,
    description: 'El trofeo más antiguo del fútbol español. La gran final de la Copa del Rey se disputa en La Cartuja con dos de los mejores equipos de La Liga.',
    partners: ['ticketmaster', 'stubhub', 'entradas'],
  },
  {
    id: 'iaaf-diamond-league-madrid-2026',
    title: 'Diamond League Madrid — Atletismo',
    sport: 'Atletismo',
    date: '2026-07-05',
    time: '19:30',
    venue: 'Estadio Vallehermoso',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/athletics-madrid.jpg',
    priceFrom: 25,
    priceTo: 120,
    description: 'Las estrellas del atletismo mundial se reúnen en Madrid para una noche eléctrica de velocidad, saltos y lanzamientos en la IAAF Diamond League.',
    partners: ['ticketmaster', 'entradas'],
  },
  {
    id: 'valencia-villarreal-2026',
    title: 'Valencia CF vs Villarreal CF — La Liga',
    sport: 'Fútbol',
    date: '2026-02-28',
    time: '18:30',
    venue: 'Estadio Mestalla',
    city: 'Valencia',
    country: 'España',
    image: '/images/events/valencia-villarreal.jpg',
    priceFrom: 40,
    priceTo: 180,
    description: 'El derbi valenciano de La Liga. Dos de los equipos más apasionados del levante español se enfrentan en el histórico Mestalla.',
    partners: ['ticketmaster', 'axs', 'elcorte'],
  },
  {
    id: 'roland-garros-2026',
    title: 'Roland Garros — Open de Francia',
    sport: 'Tenis',
    date: '2026-05-25',
    time: '11:00',
    venue: 'Stade Roland Garros',
    city: 'París',
    country: 'Francia',
    image: '/images/events/roland-garros.jpg',
    priceFrom: 55,
    priceTo: 650,
    description: 'El Grand Slam de la tierra batida. El más prestigioso torneo sobre polvo de ladrillo con los mejores tenistas del mundo luchando por el título en París.',
    partners: ['ticketmaster', 'stubhub', 'viagogo'],
  },
  {
    id: 'tour-de-france-bilbao-2026',
    title: 'Tour de France — Gran Salida Bilbao',
    sport: 'Ciclismo',
    date: '2026-07-04',
    time: '12:00',
    venue: 'Gran Vía de Bilbao',
    city: 'Bilbao',
    country: 'España',
    image: '/images/events/tour-de-france.jpg',
    priceFrom: 0,
    priceTo: 110,
    description: 'La Grande Boucle arranca desde el País Vasco. Vive la salida del Tour de France desde el corazón de Bilbao con los campeones del ciclismo mundial.',
    partners: ['ticketmaster', 'entradas', 'axs'],
  },
  {
    id: 'balonmano-mundial-madrid-2026',
    title: 'Campeonato del Mundo de Balonmano — Fase de Grupos',
    sport: 'Balonmano',
    date: '2026-01-15',
    time: '20:00',
    venue: 'WiZink Center',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/handball-madrid.jpg',
    priceFrom: 30,
    priceTo: 150,
    description: 'El mundo del balonmano se da cita en Madrid. Velocidad, fuerza y espectáculo en los partidos de la fase de grupos del Campeonato Mundial.',
    partners: ['ticketmaster', 'ticketea', 'elcorte'],
  },
  {
    id: 'euroleague-final-four-2026',
    title: 'EuroLeague Basketball — Final Four',
    sport: 'Baloncesto',
    date: '2026-05-22',
    time: '18:00',
    venue: 'Palau Sant Jordi',
    city: 'Barcelona',
    country: 'España',
    image: '/images/events/euroleague-basketball.jpg',
    priceFrom: 70,
    priceTo: 380,
    description: 'Los cuatro mejores equipos de Europa compiten por el título de EuroLeague en el icónico Palau Sant Jordi de Barcelona. El cenit del baloncesto europeo.',
    partners: ['ticketmaster', 'axs', 'stubhub'],
  },
  {
    id: 'ufc-fight-night-madrid-2026',
    title: 'UFC Fight Night — Madrid',
    sport: 'MMA',
    date: '2026-04-05',
    time: '19:00',
    venue: 'WiZink Center',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/ufc-madrid.jpg',
    priceFrom: 80,
    priceTo: 500,
    description: 'Las artes marciales mixtas llegan a Madrid. Una noche de combates épicos con los mejores luchadores del mundo en la jaula del WiZink Center.',
    partners: ['ticketmaster', 'axs', 'viagogo'],
  },
  {
    id: 'ironman-barcelona-2026',
    title: 'IRONMAN Barcelona — Triatlón',
    sport: 'Triatlón',
    date: '2026-10-04',
    time: '07:00',
    venue: 'Playa de la Mar Bella',
    city: 'Barcelona',
    country: 'España',
    image: '/images/events/ironman-barcelona.jpg',
    priceFrom: 450,
    priceTo: 520,
    description: '3,8 km de natación, 180 km en bici y 42 km corriendo. El IRONMAN Barcelona reúne a miles de atletas en la costa mediterránea. Un día para la historia personal.',
    partners: ['ticketmaster', 'entradas'],
  },
  {
    id: 'davis-cup-finals-madrid-2026',
    title: 'Davis Cup Finals — Grupos',
    sport: 'Tenis',
    date: '2026-11-21',
    time: '12:00',
    venue: 'Palacio de Deportes de la Comunidad',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/davis-cup.jpg',
    priceFrom: 40,
    priceTo: 220,
    description: 'La Copa Davis vuelve a Madrid. Las mejores selecciones nacionales de tenis del mundo compiten por el torneo por equipos más importante del circuito.',
    partners: ['ticketmaster', 'axs', 'entradas'],
  },
  {
    id: 'derbi-sevillano-2026',
    title: 'Derbi Sevillano: Sevilla FC vs Real Betis',
    sport: 'Fútbol',
    date: '2026-04-19',
    time: '18:00',
    venue: 'Estadio Ramón Sánchez-Pizjuán',
    city: 'Sevilla',
    country: 'España',
    image: '/images/events/sevilla-derby.jpg',
    priceFrom: 65,
    priceTo: 310,
    description: 'El derbi más apasionado de Andalucía. Sevilla FC y Real Betis se enfrentan en el Sánchez-Pizjuán en uno de los partidos con más ambiente de España.',
    partners: ['ticketmaster', 'stubhub', 'viagogo'],
  },
  {
    id: 'formula-e-madrid-2026',
    title: 'Fórmula E — Madrid ePrix',
    sport: 'Motor',
    date: '2026-04-26',
    time: '14:30',
    venue: 'Circuito Urbano IFEMA',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/formula-e-madrid.jpg',
    priceFrom: 55,
    priceTo: 260,
    description: 'El futuro de la movilidad compite en el corazón de Madrid. El ePrix de Madrid reúne a los pilotos más rápidos del campeonato de Fórmula E en un trazado urbano.',
    partners: ['ticketmaster', 'axs'],
  },
  {
    id: 'maraton-madrid-2026',
    title: 'Maratón de Madrid Rock \'n\' Roll',
    sport: 'Maratón',
    date: '2026-04-26',
    time: '09:00',
    venue: 'Paseo de la Castellana',
    city: 'Madrid',
    country: 'España',
    image: '/images/events/madrid-marathon.jpg',
    priceFrom: 60,
    priceTo: 120,
    description: 'Miles de corredores de todo el mundo toman las calles de Madrid en el maratón más popular de España. 42 km entre los monumentos más emblemáticos de la capital.',
    partners: ['ticketmaster', 'entradas', 'ticketea'],
  },
  {
    id: 'espana-portugal-nations-league-2026',
    title: 'España vs Portugal — UEFA Nations League',
    sport: 'Fútbol',
    date: '2026-10-11',
    time: '20:45',
    venue: 'Estadio Benito Villamarín',
    city: 'Sevilla',
    country: 'España',
    image: '/images/events/spain-portugal.jpg',
    priceFrom: 85,
    priceTo: 420,
    description: 'El derbi ibérico de las selecciones nacionales. España y Portugal se enfrentan en el Benito Villamarín en un partido de máxima rivalidad por la Nations League.',
    partners: ['ticketmaster', 'stubhub', 'axs'],
  },
  {
    id: 'derbi-vasco-2026',
    title: 'Real Sociedad vs Athletic Club — Derbi Vasco',
    sport: 'Fútbol',
    date: '2026-03-07',
    time: '18:30',
    venue: 'Reale Arena',
    city: 'San Sebastián',
    country: 'España',
    image: '/images/events/real-sociedad-athletic.jpg',
    priceFrom: 55,
    priceTo: 240,
    description: 'El apasionante derbi vasco entre dos de los equipos con más historia e identidad del fútbol español. Una tarde de pasión y rivalidad en el Reale Arena.',
    partners: ['ticketmaster', 'entradas', 'elcorte'],
  },
  {
    id: 'campeonato-europa-atletismo-2026',
    title: 'Campeonato de Europa de Atletismo',
    sport: 'Atletismo',
    date: '2026-08-12',
    time: '10:00',
    venue: 'Estadio Olímpico',
    city: 'Berlín',
    country: 'Alemania',
    image: '/images/events/european-athletics.jpg',
    priceFrom: 40,
    priceTo: 210,
    description: 'Los mejores atletas europeos compiten por las medallas en Berlín. Diez días de emoción con velocistas, saltadores, lanzadores y fondistas de primer nivel.',
    partners: ['ticketmaster', 'entradas', 'axs'],
  },
  {
    id: 'ucl-final-wembley-2026',
    title: 'Final UEFA Champions League — Wembley',
    sport: 'Fútbol',
    date: '2026-05-30',
    time: '21:00',
    venue: 'Wembley Stadium',
    city: 'Londres',
    country: 'Reino Unido',
    image: '/images/events/ucl-final.jpg',
    priceFrom: 350,
    priceTo: 2500,
    description: 'La noche más grande del fútbol europeo. La Final de la UEFA Champions League se disputa en el legendario Wembley Stadium de Londres ante 90.000 espectadores.',
    partners: ['stubhub', 'viagogo', 'ticketmaster', 'axs'],
    featured: true,
  },
]

export function getEventById(id: string): Event | undefined {
  return events.find((e) => e.id === id)
}

export function getFeaturedEvents(): Event[] {
  return events.filter((e) => e.featured)
}

export function getEventsByCategory(sport: string): Event[] {
  return events.filter((e) => e.sport === sport)
}

export const SPORTS: Sport[] = [
  'Fútbol', 'Motor', 'Tenis', 'Ciclismo', 'Atletismo',
  'Baloncesto', 'MMA', 'Triatlón', 'Balonmano', 'Maratón',
]
